name: Build or destroy infrastructure

on:
  workflow_dispatch: 
    inputs:
      action_type:
        description: "Type of action you want to take('build' or 'destroy')"
        required: true

env: 
    AWS_REGION:  ap-southeast-2
    IAM_role: "arn:aws:iam::252874068638:role/GitHubAction-AssumeRoleWithAction"
permissions: 
    id-token: write
    contents: read


jobs:
    build: 
        name: "build"
        runs-on: ubuntu-latest
        if: inputs.action_type == 'build'

      #  run:
        #   working-directory: "."
        steps:
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@master #import a library
              with: 
                role-to-assume: ${{ env.IAM_role}}
                aws-region: ${{ env.AWS_REGION }}
              
            - uses: actions/checkout@v3
            - uses: hashicorp/setup-terraform@v2
        
            - name: Terraform fmt
              id: fmt
              run: terraform fmt -check
              continue-on-error: true
            
            - name: Terraform Init
              id: init
              run: terraform init
            
            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color
            
            - name: Terraform Plan
              id: plan
              run: terraform plan -no-color
              continue-on-error: true

            - name: Terraform Apply
              id: appky
              run: terraform apply -auto-approve
              continue-on-error: false

      

